spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false

server:
  error:
    include-message: always
  forward-headers-strategy: native
  port: 8081
  servlet:
    context-path: /codebreaker-solitaire

schedule:
  cron: 0 0 0 * * ?
  zone: UTC
  stale-game-days: 14
