spring:
  jackson:
    deserialization:
      accept-float-as-int: false
  datasource:
    url: jdbc:h2:file:./codebreaker-h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql

server:
  error:
    include-message: always
  forward-headers-strategy: native
  port: 8081
  servlet:
    context-path: /codebreaker

schedule:
  cron: 0 0 0 * * ?
  zone: UTC
  stale-code-days: 30